# Generated by Django 3.1 on 2020-08-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_products_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='myApp.Products'),
        ),
    ]
