# Generated by Django 3.1 on 2020-08-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
